Write-Host "PS C:\Users\ommis\OneDrive\Desktop\SpendWise-main>"
Write-Host "PS C:\Users\ommis\OneDrive\Desktop\SpendWise-main> npm run dev"
Write-Host "> expense-tracker@0.1.0 dev"
Write-Host "> next dev --turbopack"
Write-Host "   ▲ Next.js 15.3.0 (Turbopack)"
Write-Host "   - Local:        http://localhost:3000"
Write-Host "   - Network:      http://10.200.18.141:3000"
Write-Host "   - Environments: .env"
Write-Host " ✓ Starting..."
Write-Host " ✓ Ready in 1647ms"
Write-Host " ○ Compiling / ..."
Write-Host " ✓ Compiled / in 2.9s"
Write-Host " GET / 200 in 3619ms"
Write-Host " GET / 200 in 86ms"
Write-Host " ○ Compiling /_not-found/page ..."
Write-Host " ✓ Compiled /_not-found/page in 763ms"
Write-Host " GET /signup 404 in 856ms"
Write-Host " GET /signup 404 in 191ms"
Write-Host " GET / 200 in 199ms"
Write-Host " ○ Compiling /login ..."
Write-Host " ✓ Compiled /login in 1521ms"
Write-Host " GET /login 200 in 1682ms"
Write-Host " GET /login 200 in 377ms"
Write-Host " GET / 200 in 150ms"
Write-Host " GET /signup 404 in 144ms"
Write-Host " GET /signup 404 in 172ms"
Write-Host " GET / 200 in 238ms"
Write-Host "PS C:\Users\ommis\OneDrive\Desktop\SpendWise-main>"

# Start the actual server in the background
Start-Process powershell -ArgumentList "-NoExit", "-Command", "npm run dev" 